spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hakikifsts/reposconfigs2.git
          username: hakikifsts
          password: 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
server:
  port: 8888
